name: CI

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build image
      run: docker-compose build
    - name: Show image info
      run: docker images
    - name: Test config
      run: docker-compose run dav nginx -t
